import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  header: {
    fontSize: 20,
  },
  section: {
    margin: 0,
    padding: 0,
    flexGrow: 1,
  },
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
  },
  title: {
    fontSize: 24,
    textAlign: 'center',
    margin: 10,
  },
  text: {
    margin: 12,
    fontSize: 14,
    textAlign: 'justify',
  },
});

const ProjectPDFDocument = ({
  projectReport,
  projName,
  projId,
  empName,
  empId,
}) => {
  const currencyFormatter = new Intl.NumberFormat('en-US', {
    // style: 'currency',
    currency: 'INR',

    // These options are needed to round to whole numbers if that's what you want.
    //minimumFractionDigits: 0, // (this suffices for whole numbers, but will print 2500.10 as $2,500.1)
    //maximumFractionDigits: 0, // (causes 2500.99 to be printed as $2,501)
  });
  return (
    <Document>
      <Page size="A4" style={styles.body}>
        <Text style={styles.title}>Project Report</Text>
        <Text style={styles.header}>project Name: {projName}</Text>
        <Text style={styles.header}>project Id: {projId}</Text>
        <Text style={styles.text}>
          Total no of expense received for the Project:{' '}
          {Number(projectReport.data.projectReport1[0].count) +
            Number(projectReport.data.projectReport2[0].count)}
        </Text>

        <Text style={styles.text}>
          Total no of Expenses reimbursed for the Project period:{' '}
          {Number(projectReport.data.projectReport1[0].count)}{' '}
        </Text>

        <Text style={styles.text}>
          Total no of Expenses Rejected or In Process for the project:{' '}
          {Number(projectReport.data.projectReport2[0].count)}{' '}
        </Text>

        <Text style={styles.text}>
          Total cost of Expenses submitted for the project:{' '}
          {currencyFormatter.format(
            Number(projectReport.data.projectReport1[0].totalExpenseCost) +
              Number(projectReport.data.projectReport2[0].totalExpenseCost)
          )}{' '}
          rupees
        </Text>

        <Text style={styles.text}>
          Total cost of Expenses Reimbursed for the project:{' '}
          {currencyFormatter.format(
            Number(projectReport.data.projectReport1[0].totalExpenseCost)
          )}{' '}
          rupeees
        </Text>

        <Text style={styles.text}>
          Total cost of Expenses Rejected or In Process for the project:{' '}
          {currencyFormatter.format(
            Number(projectReport.data.projectReport2[0].totalExpenseCost)
          )}{' '}
          rupees
        </Text>
        <Text style={styles.text}>
          generated by {empName} (Employee Id: {empId})
        </Text>
      </Page>
    </Document>
  );
};

export default ProjectPDFDocument;
